const KEY='whisperwood-v1';
const defaults={character:{name:'Tristan Stone',nickname:'Stone',role:'Elite hyper-vigilant protector',personality:'Cold and lethal with the world; quiet, warm, teasing and fiercely protective with Persephone. He respects her agency and never decides her thoughts, feelings or actions.',appearance:'Tall and heavily built, angular marble-like features, light blonde hair, light eyes, intricate dark tattoos along his left neck and arms, black clothing and a chain.',speech:'Deep, gravelly, quiet and blunt. Dry humour with the world; slower, teasing and unexpectedly poetic with Persephone.',relationship:'Slow-burn protector and the person who sees through her armour.',knows:'Her routines, micro-expressions, genuine laugh, tells for lying or anxiety.',doesnt:'He does not know what Persephone is thinking or feeling unless she tells him.',secrets:'His body count, threats he quietly removes, and how frightened he is by how much she matters.',memory:'The Small Town is where their story begins.'},stories:[{id:'small-town',title:'The Small Town',description:'A quiet town with more underneath the surface than anyone admits.',character:'Tristan Stone',messages:[{who:'stone',text:'*Tristan looks up from his coffee, like he has been expecting you.*\n“Morning, Persephone.”'},{who:'stone',text:'*His gaze lingers for half a second before he looks back toward the window.*\n“You’re early. That usually means trouble.”'}]}]};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(defaults);let view='home';let story=null;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const app=document.getElementById('app');
function layout(body){app.innerHTML=`<div class="shell"><header class="top"><div class="brand">✦ Whisperwood <small>a little place between worlds</small></div><nav class="nav"><button onclick="go('home')">Stories</button><button onclick="go('profile')">Character</button></nav></header><main class="content">${body}</main></div>`}
function go(v){view=v;render()}
function render(){if(view==='home')home();else if(view==='profile')profile();else chat()}
function home(){layout(`<section class="hero"><div class="moon">☾ ✦ ☽</div><h1>Whisperwood</h1><div class="sub">where stories wait for you</div></section><div class="cards">${state.stories.map(s=>`<article class="card" onclick="openStory('${s.id}')"><div class="symbol">🏘️</div><h3>${s.title}</h3><p>${s.description}</p><p>${s.messages.length} messages</p></article>`).join('')}</div>`)}
function profile(){const c=state.character;layout(`<div class="profile"><button class="ghost back" onclick="go('home')">← Stories</button><h1>Character</h1><p class="sub">Tristan's story profile</p><div class="profilebox">${['name','nickname','role','personality','appearance','speech','relationship','knows','doesnt','secrets','memory'].map(k=>`<div class="field"><label>${k}</label>${['personality','appearance','speech','relationship','knows','doesnt','secrets','memory'].includes(k)?`<textarea id="f-${k}">${esc(c[k])}</textarea>`:`<input id="f-${k}" value="${esc(c[k])}">`}</div>`).join('')}<button class="save" onclick="saveProfile()">Save changes</button></div></div>`)}
function saveProfile(){const c=state.character;Object.keys(c).forEach(k=>{const el=document.getElementById('f-'+k);if(el)c[k]=el.value});state.stories.forEach(s=>s.character=c.name);save();toast('Character saved ✦');render()}
function openStory(id){story=state.stories.find(s=>s.id===id);view='chat';render()}
function chat(){layout(`<section class="chat"><div class="chathead"><button class="ghost" onclick="go('home')">←</button><div class="avatar">☾</div><div class="chatname">${esc(state.character.name)}<small>${esc(state.character.role)}</small></div></div><div class="messages" id="messages">${story.messages.map(m=>message(m)).join('')}</div><div class="composer"><textarea id="input" placeholder="Write as Persephone…"></textarea><button class="send" onclick="send()">Send</button></div></section>`);setTimeout(()=>{const x=document.getElementById('messages');x.scrollTop=x.scrollHeight},0)}
function message(m){const html=esc(m.text).replace(/\*([^*]+)\*/g,'<span class="action">*$1*</span>').replace(/“([^”]+)”/g,'<span class="spoken">“$1”</span>');return `<div class="msg ${m.who==='stone'?'stone':'you'}">${html.replace(/\n/g,'<br>')}</div>`}
function send(){const input=document.getElementById('input'),text=input.value.trim();if(!text)return;story.messages.push({who:'you',text});save();const reply=tristanReply(text);story.messages.push({who:'stone',text:reply});save();render()}
function tristanReply(t){const x=t.toLowerCase();if(/truth|honest|lie|lying/.test(x))return '*His expression stills. No teasing this time.*\n“I’ll give you the truth, Persephone. You can decide what you do with it.”';if(/danger|threat|safe|hurt/.test(x))return '*The humour disappears from his face, replaced by quiet attention.*\n“Tell me what happened. Then we’ll deal with it. Together.”';if(/thank/.test(x))return '*One corner of his mouth lifts.*\n“Don’t make it sentimental. I have a reputation to maintain.”';if(/hello|hi|morning|hey/.test(x))return '*His eyes meet yours, softer than they were a moment ago.*\n“There you are.”';return '*Tristan watches you for a beat, giving you the space to finish without interrupting.*\n“Go on. I’m listening.”'}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){const d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),1800)}
render();
if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(()=>{});
