const STORAGE='whisperwood-v2';
const LEGACY='whisperwood-v1';
const DEFAULT={version:2,profile:{name:'Tristan Stone',nickname:'Stone',role:'Elite hyper-vigilant protector',personality:'Cold and lethal with the world; warm, dryly teasing and unexpectedly gentle with Persephone.',appearance:'Tall, heavily built, light blonde hair, light eyes, angular marble-like features, dark tattoos on his neck and arms, usually dressed in black.',voice:'Deep, gravelly and quiet. Blunt realism and dry humour; slower, teasing and poetic with Persephone.',relationship:'Protector, slow-burn confidant and the one person who sees behind the armour.',knows:'Persephone’s routines, micro-expressions, genuine laugh, and the tells she has when she is lying or anxious.',doesntKnow:'Whatever Persephone has not chosen to reveal. He never fills in her thoughts for her.',secrets:'His history and the full scale of the violence he has survived and committed.',memory:'He remembers what matters, especially the small things Persephone mentions in passing.'},stories:[{id:'small-town',title:'The Small Town',description:'A quiet town with old secrets, slow-burning danger and one man who always seems to notice when you enter the room.',icon:'☾',meta:['Slow burn','Mystery','Protector'],messages:[{who:'tristan',text:'*Tristan looks up from his coffee, like he’s been expecting you.* “You’re late, Trouble.”'},{who:'user',text:'I’m two minutes late.'},{who:'tristan',text:'*The corner of his mouth lifts.* “Two minutes is practically a scandal around here.”'}]}]};
let state=load();let view='home';let activeStoryId=null;
const app=document.getElementById('app');
function load(){try{const raw=localStorage.getItem(STORAGE)||localStorage.getItem(LEGACY);if(raw){const parsed=JSON.parse(raw);return {...DEFAULT,...parsed,profile:{...DEFAULT.profile,...(parsed.profile||{})},stories:Array.isArray(parsed.stories)&&parsed.stories.length?parsed.stories:DEFAULT.stories};}}catch(e){}return structuredClone(DEFAULT)}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function initials(name){return name.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function parseMessage(text){let safe=esc(text);safe=safe.replace(/\*([^*]+)\*/g,'<span class="action">$1</span>');safe=safe.replace(/“([^”]+)”/g,'<span class="spoken">“$1”</span>');return safe.replace(/\n/g,'<br>')}
function shell(content){app.innerHTML=`<div class="app-shell"><header class="topbar"><div class="brand" data-action="home"><span class="brand-mark"></span><span><span class="brand-title">Whisperwood</span><span class="brand-sub">a little place between worlds</span></span></div><nav class="nav"><button data-action="home">Stories</button><button data-action="profile">Characters</button></nav></header>${content}</div>`}
function home(){view='home';activeStoryId=null;shell(`<section class="hero"><div class="hero-copy"><div class="eyebrow">Your private story world</div><h1>Welcome to <em>Whisperwood</em></h1><p>A little pocket of moonlight, secrets and stories. Choose a world, step inside, and decide what Persephone does next.</p></div></section><div class="section-head"><div><h2>Your stories</h2><p>Pick up wherever you left off.</p></div></div><section class="stories-grid">${state.stories.map(s=>`<article class="story-card" data-story="${esc(s.id)}"><div class="story-icon">${s.icon}</div><h3>${esc(s.title)}</h3><p>${esc(s.description)}</p><div class="meta">${s.meta.map(x=>`<span>${esc(x)}</span>`).join(' · ')}</div></article>`).join('')}</section>`)}
function chat(){const story=state.stories.find(s=>s.id===activeStoryId);if(!story){home();return}const p=state.profile;shell(`<section class="page-panel"><div class="story-header"><button class="back" data-action="home" aria-label="Back">←</button><div class="avatar">${initials(p.name)}</div><div class="story-title"><strong>${esc(p.name)}</strong><span>${esc(p.nickname)} · ${esc(p.role)}</span></div><button class="ghost-btn" data-action="profile">Profile</button></div><div class="messages" id="messages">${story.messages.map(m=>`<div class="msg ${m.who==='user'?'user':'tristan'}"><div class="msg-label">${m.who==='user'?'Persephone':esc(p.name)}</div><div class="bubble">${parseMessage(m.text)}</div></div>`).join('')}</div><form class="composer" id="composer"><textarea id="reply" placeholder="Write as Persephone…" autocomplete="off"></textarea><button class="send" type="submit">Send</button></form></section>`);scrollMessages()}
function profile(){view='profile';activeStoryId=null;const p=state.profile;shell(`<section class="page-panel"><div class="profile-wrap"><div class="profile-head"><div class="avatar">${initials(p.name)}</div><div><h1>${esc(p.name)}</h1><p>Character profile · changes apply across your stories</p></div></div><form id="profile-form"><div class="form-grid">${field('Name','name',p.name)}${field('Nickname','nickname',p.nickname)}${field('Role','role',p.role)}${field('Relationship to me','relationship',p.relationship)}${area('Personality','personality',p.personality)}${area('Appearance','appearance',p.appearance)}${area('How they speak','voice',p.voice)}${area('Things they know','knows',p.knows)}${area('Things they don’t know','doesntKnow',p.doesntKnow)}${area('Secrets','secrets',p.secrets)}${area('Memory','memory',p.memory)}</div><div class="profile-actions"><button type="button" class="ghost-btn" data-action="home">Cancel</button><button class="save" type="submit">Save character</button></div></form></div></section>`)}
function field(label,key,value){return `<div class="field"><label for="${key}">${label}</label><input id="${key}" name="${key}" value="${esc(value)}"></div>`}
function area(label,key,value){return `<div class="field full"><label for="${key}">${label}</label><textarea id="${key}" name="${key}">${esc(value)}</textarea></div>`}
function render(){if(view==='chat')chat();else if(view==='profile')profile();else home()}
function scrollMessages(){requestAnimationFrame(()=>{const el=document.getElementById('messages');if(el)el.scrollTop=el.scrollHeight})}
function toast(text){const t=document.createElement('div');t.className='toast';t.textContent=text;document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}
function makeReply(input,story){const q=input.toLowerCase();const name=state.profile.name;const replies=[{keys:['late','minutes','time'],reply:`*${name} glances at the clock, then back at you.* “I noticed. I also noticed you look far too pleased with yourself.”`},{keys:['why','what','happen'],reply:`*His expression settles, all the teasing falling away for a beat.* “Because something changed. And I’d rather you hear it from me than from someone else.”`},{keys:['okay','fine','sure'],reply:`*${name} studies you for a quiet second.* “That sounded suspiciously like surrender. I’ll pretend I didn’t hear it.”`},{keys:['danger','safe','afraid'],reply:`*The humour leaves his face. He keeps his distance, voice low.* “You’re allowed to be afraid. Just don’t let fear make the decision for you.”`}];const hit=replies.find(r=>r.keys.some(k=>q.includes(k)));if(hit)return hit.reply;const open=[`*${name} watches you over the rim of his cup, clearly deciding how much trouble to encourage.* “Go on, Trouble. I’m listening.”`,`*A quiet breath of amusement escapes him.* “You really do have a talent for making simple things complicated.”`,`*${name} tilts his head, studying you without trying to decide anything for you.* “Your move, Persephone.”`];return open[Math.floor(Math.random()*open.length)]}
function send(text){const story=state.stories.find(s=>s.id===activeStoryId);if(!story||!text.trim())return;story.messages.push({who:'user',text:text.trim()});save();render();setTimeout(()=>{const fresh=state.stories.find(s=>s.id===activeStoryId);if(!fresh)return;fresh.messages.push({who:'tristan',text:makeReply(text,fresh)});save();render()},420)}
document.addEventListener('click',e=>{const card=e.target.closest('[data-story]');if(card){activeStoryId=card.dataset.story;view='chat';render();return}const action=e.target.closest('[data-action]')?.dataset.action;if(action){if(action==='home')home();if(action==='profile')profile()}});
document.addEventListener('submit',e=>{if(e.target.id==='composer'){e.preventDefault();const box=document.getElementById('reply');const text=box.value;box.value='';send(text)}if(e.target.id==='profile-form'){e.preventDefault();const fd=new FormData(e.target);state.profile={...state.profile};for(const [k,v] of fd.entries())state.profile[k]=v;state.stories.forEach(s=>s.messages=s.messages);save();toast('Character saved ✦');setTimeout(()=>{view='profile';render()},350)}});
document.addEventListener('keydown',e=>{if(e.target.id==='reply'&&e.key==='Enter'&&!e.shiftKey){e.preventDefault();document.getElementById('composer')?.requestSubmit()}});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
